name: slack-bot-build

on:
  workflow_call:
  push:
    branches:
      - "main"
      - "fix/*"
      - "feature/*"
    paths-ignore:
      - "infra/"
      - "*.md"

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  imageName: "vivitian/slack-ai-bot"
  imageTag: "dev"

jobs:
  c1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Tag with "version"
        if: github.ref == 'refs/heads/main'
        run: |
          echo "imageTag=$(cat version)" >> $GITHUB_ENV

      - name: Tag on fix branches
        if: startsWith(github.ref, 'refs/heads/fix/')
        run: |
          echo "imageTag=dev-${GITHUB_SHA::6}" >> $GITHUB_ENV

      - name: Tag on fix branches
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: |
          echo "imageTag=dev-${GITHUB_SHA::6}" >> $GITHUB_ENV

      - name: Debug - Image Tag
        run: |
          echo "${{ env.imageTag }}"
          echo "### App Version" >> $GITHUB_STEP_SUMMARY

      - name: Docker - Build
        run: |
          docker build -t ${{ env.imageName}}:${{ env.imageTag}} .
          echo "### Docker" >> $GITHUB_STEP_SUMMARY
          echo "Built Image \`${{ env.imageName }}:${{ env.imageTag }}\`" >> $GITHUB_STEP_SUMMARY

      - name: Docker Scan - Snyk Vulnerability Scanner
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.imageName }}:${{ env.imageTag }}
          args: --file=dockerfile --severity-threshold=high

      - name: Scan -Publish Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Docker Hub - Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker - Push
        id: docker_push
        run: |
          docker push ${{ env.imageName }}:${{ env.imageTag }}
          echo "Pushed Image \ '${{ env.imageName }}:${{ env.imageTag }}'" >> $GITHUB_STEP_SUMMARY

      - name: Debug - Image digest
        run: |
          echo ${{ steps.docker_push.outputs.digest }}
          echo "Image Digest\ '{{ steps.docker_push.outputs.digest}}\'" >> $GITHUB_STEP_SUMMARY
